name: Auto-version on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  version:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Bump Version
        id: bump_version
        run: |
          set -e
          LAST_TAG="${TAG#v}"
          TITLE="${{ github.event.pull_request.title }}"
          MAJOR=$(echo "$LAST_TAG" | cut -d. -f1)
          MINOR=$(echo "$LAST_TAG" | cut -d. -f2)
          PATCH=$(echo "$LAST_TAG" | cut -d. -f3)
          if [[ -z "$TITLE" ]]; then
            echo "No PR title found. Exiting."
            exit 0
          fi
          if [[ "$TITLE" =~ ^[a-zA-Z]+!: ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            echo "Major version bump."
          elif [[ "$TITLE" =~ ^feat: ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            echo "Minor version bump."
          elif [[ "$TITLE" =~ ^fix: ]]; then
            PATCH=$((PATCH + 1))
            echo "Patch version bump."
          else
            echo "No version bump, exiting."
            exit 0
          fi
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create Tag
        if: env.NEW_TAG != ''
        run: |
          set -e
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Create GitHub Release
        if: env.NEW_TAG != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}
